### ISSUE TITLE
cumcord does not run powercord and bd plugins

### ISSUE THREAD

**Issue by kekkodance** [lexyclear/Discord3rdparties#1]
All of what was said is fixed now I will walk away cause Im a dumdum yeah!

**Comment by lexyclear** [comment]
> are you high?
> 
> armcord doesn't run bd plugins or powercord, it just injects cumcord. vizality is dead as shit kernel, not KERNAL and the stock discord client isnt called "reg", it's stable. and you clearly do not list all modifications for discord as there's plenty more, these are just the main ones.

Cumcord runs as a plugin for other mods (BetterDiscord, Powercord, GooseMod, Vizality) so you only have to write code once my bad miswrote it.

I am drunk as fuck.

I'll fix the spelling.

regular is just my writing for normal or just discord lol not changing that.

feel free to link more that are currently active.

Vizality still looks pretty active...

**Comment by CanadaHonk** [comment]
> what you said was not helpful with the insults btw and I'd like you to refrain in the future.

Then you edited their original post insulting them?

**Comment by CanadaHonk** [comment]
> Kernel(dead)

Kernel isn't dead?

**Comment by kekkodance** [comment]
> Cumcord runs as a plugin for other mods (BetterDiscord, Powercord, GooseMod, Vizality) so you only have to write code once my bad miswrote it.
> 
> I am drunk as fuck.
> 
> I'll fix the spelling.
> 
> regular is just my writing for normal or just discord lol not changing that.
> 
> feel free to link more that are currently active.
> 
> Vizality still looks pretty active...
> 
> what you said was not helpful with the insults btw and I'd like you to refrain in the future.

such rudeness was not my plan, you edit my message insulting me further and not ignoring the slight poke, that just proves your childishness. also kernel is not dead, i am running it atm.

**Comment by sehnryr** [comment]
Just to confirm some of your questionings, [Kernel](https://github.com/kernel-mod) is not discontinued as their repositories were updated not long ago and [Vizality](https://github.com/vizality) seems dead on Github but they are quite active on Discord (see spoiler below).

<details> 
  <summary>image</summary>
  <img src="https://user-images.githubusercontent.com/40632486/166895428-0e30b3fd-2039-4568-b747-df9473dee6c9.png"/>
</details>
