### ISSUE TITLE
Ripcord

### ISSUE THREAD

**Issue by jameslinimk** [lexyclear/Discord3rdparties#3]
Add [Ripcord](https://cancel.fm/ripcord/) to the list. It is VERY lightweight, written in cpp, has vc support, and slack support.

**Comment by lexyclear** [comment]
its discontinued

**Comment by sehnryr** [comment]
I've talked with the author of Ripcord @randrew and he confirmed me that the project was just on hiatus since he is busy with other things. So it is not discontinued or anything, and despite some bugs with the new features on servers, Ripcord still works fine.
